# Generated by Django 4.0.1 on 2022-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0006_student_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
