# Generated by Django 4.0.2 on 2022-02-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTodo', '0002_rename_createdate_todo_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('H', 'High'), ('L', 'Low')], max_length=50),
        ),
    ]
